version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    groups:
      types:
        patterns:
          - "@types/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "typescript-eslint"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
